databases:
  - name: shoponlinenewyork
    databaseName: shoponlinenewyork
    user: shoponlinenewyork
    plan: free

services:
  - type: web
    name: shoponlinenewyork
    env: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: shoponlinenewyork
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false